name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [18.x, 20.x, 22.x]
=======
        node-version: [22.x]
>>>>>>> e6e3fcaf65e8b8ebf39aecc3e573066aef2c4f0f

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
<<<<<<< HEAD
        npx webpack
=======
        npm run build
>>>>>>> e6e3fcaf65e8b8ebf39aecc3e573066aef2c4f0f
